apiVersion: skaffold/v2alpha3
kind: Config
deploy:
  kubectl:
    manifests:
      - ./infra/k8s/*
      - ./infra/k8s-dev/*
build:
  local:
    push: false
  artifacts:
    - image: accounts
      context: apps/tusks-accounts-service
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: 'src/**/*.ts'
            dest: .

    - image: client
      context: apps/tusks-client
      docker:
        dockerfile: Dockerfile
      sync:
        infer:
          - 'src/**/*.tsx'
          - 'src/**/*.ts'
          - 'next.config.js'

    - image: boards
      context: apps/tusks-board-service
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: 'src/**/*.ts'
            dest: .

    - image: auth
      context: apps/tusks-auth-service
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: 'src/**/*.ts'
            dest: .

    - image: payments
      context: apps/tusks-payments-service
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: 'src/**/*.ts'
            dest: .

    - image: email
      context: apps/email-service
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: 'src/**/*.ts'
            dest: .
