apiVersion: skaffold/v2alpha3
kind: Config
deploy:
  kubectl:
    manifests:
      - ./infra/k8s/*
      - ./infra/k8s-dev/*
build:
  local:
    push: false
  artifacts:
    - image: accounts
      docker:
        dockerfile: ./docker/Dockerfile.accounts
      sync:
        infer:
          - 'apps/tusks-accounts-service/src/**/*.ts'

    - image: auth
      docker:
        dockerfile: ./docker/Dockerfile.auth
      sync:
        infer:
          - 'apps/tusks-auth-service/src/**/*.ts'

    - image: client
      docker:
        dockerfile: ./docker/Dockerfile.client
      sync:
        infer:
          - 'apps/tusks-client/src/**/*.tsx'
          - 'apps/tusks-client/src/**/*.ts'
          - 'apps/tusks-client/next.config.js'

    - image: boards
      docker:
        dockerfile: ./docker/Dockerfile.boards
      sync:
        infer:
          - 'apps/tusks-board-service/src/**/*.ts'

    - image: payments
      docker:
        dockerfile: ./docker/Dockerfile.payments
      sync:
        infer:
          - 'apps/tusks-payments-service/src/**/*.ts'

    - image: email
      docker:
        dockerfile: ./docker/Dockerfile.email
      sync:
        infer:
          - 'apps/api-email-service/src/**/*.ts'
