apiVersion: apps/v1
kind: Deployment
metadata:
  name: accounts-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: accounts
  template:
    metadata:
      labels:
        app: accounts
    spec:
      containers:
        - name: accounts
          image: accounts
          # resources:
          #   limits:
          #     memory: 512Mi
          #     cpu: '500m'
          env:
            - name: JWT_ACCESS_TOKEN_SIGNATURE
              valueFrom:
                secretKeyRef:
                  name: env-config
                  key: JWT_ACCESS_TOKEN_SIGNATURE

            - name: JWT_REFRESH_TOKEN_SIGNATURE
              valueFrom:
                secretKeyRef:
                  name: env-config
                  key: JWT_REFRESH_TOKEN_SIGNATURE

            - name: MONGO_URI
              valueFrom:
                secretKeyRef:
                  name: env-config
                  key: MONGO_URI

            - name: PORT
              valueFrom:
                secretKeyRef:
                  name: env-config
                  key: PORT

            - name: SPOTIFY_REDIRECT_URI
              valueFrom:
                secretKeyRef:
                  name: env-config
                  key: SPOTIFY_REDIRECT_URI

            - name: SPOTIFY_SECRET
              valueFrom:
                secretKeyRef:
                  name: env-config
                  key: SPOTIFY_SECRET

            - name: SPOTIFY_ID
              valueFrom:
                secretKeyRef:
                  name: env-config
                  key: SPOTIFY_ID

            - name: NATS_CLIENT_ID
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name

            - name: NATS_CLUSTER_ID
              value: tuskui

            - name: NATS_URL
              value: 'http:/nats-srv:4222/'
---
apiVersion: v1
kind: Service
metadata:
  name: accounts-srv
spec:
  selector:
    app: accounts
  ports:
    - name: accounts
      protocol: TCP
      port: 3000
      targetPort: 3000
