apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: auth
  template:
    metadata:
      labels:
        app: auth
    spec:
      containers:
        - name: auth
          image: auth
          # resources:
          #   limits:
          #     memory: 512Mi
          #     cpu: '500m'
          env:
            - name: JWT_OTP_TOKEN_SIGNATURE
              valueFrom:
                secretKeyRef:
                  name: env-config
                  key: JWT_OTP_TOKEN_SIGNATURE

            - name: JWT_ACCESS_TOKEN_SIGNATURE
              valueFrom:
                secretKeyRef:
                  name: env-config
                  key: JWT_ACCESS_TOKEN_SIGNATURE

            - name: JWT_REFRESH_TOKEN_SIGNATURE
              valueFrom:
                secretKeyRef:
                  name: env-config
                  key: JWT_REFRESH_TOKEN_SIGNATURE

            - name: TOTP_AUTHENTICATOR_SECRET
              valueFrom:
                secretKeyRef:
                  name: env-config
                  key: TOTP_AUTHENTICATOR_SECRET

            - name: MONGO_URI
              valueFrom:
                secretKeyRef:
                  name: env-config
                  key: MONGO_URI

            - name: PORT
              valueFrom:
                secretKeyRef:
                  name: env-config
                  key: PORT

            - name: NATS_CLIENT_ID
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name

            - name: NATS_CLUSTER_ID
              value: tuskui
            - name: NATS_URL
              value: 'http:/nats-srv:4222/'

---
apiVersion: v1
kind: Service
metadata:
  name: auth-srv
spec:
  selector:
    app: auth
  ports:
    - name: auth
      protocol: TCP
      port: 3000
      targetPort: 3000
