apiVersion: apps/v1
kind: Deployment
metadata:
  name: boards-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: boards
  template:
    metadata:
      labels:
        app: boards
    spec:
      containers:
        - name: boards
          image: boards
          # resources:
          #   limits:
          #     memory: 912Mi
          #     cpu: '900m'
          env:
            - name: JWT_ACCESS_TOKEN_SIGNATURE
              valueFrom:
                secretKeyRef:
                  name: env-config
                  key: JWT_ACCESS_TOKEN_SIGNATURE

            - name: JWT_REFRESH_TOKEN_SIGNATURE
              valueFrom:
                secretKeyRef:
                  name: env-config
                  key: JWT_REFRESH_TOKEN_SIGNATURE

            - name: MONGO_URI
              valueFrom:
                secretKeyRef:
                  name: env-config
                  key: MONGO_URI

            - name: CLOUDINARY_API_KEY
              valueFrom:
                secretKeyRef:
                  name: env-config
                  key: CLOUDINARY_API_KEY

            - name: CLOUDINARY_CLOUD_NAME
              valueFrom:
                secretKeyRef:
                  name: env-config
                  key: CLOUDINARY_CLOUD_NAME

            - name: CLOUDINARY_API_SECRET
              valueFrom:
                secretKeyRef:
                  name: env-config
                  key: CLOUDINARY_API_SECRET

            - name: UNSPLASH_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: env-config
                  key: UNSPLASH_ACCESS_KEY

            - name: S3_BUCKET_AWS
              valueFrom:
                secretKeyRef:
                  name: env-config
                  key: S3_BUCKET_AWS

            - name: REGION_AWS
              valueFrom:
                secretKeyRef:
                  name: env-config
                  key: REGION_AWS

            - name: ACCESS_KEY_ID_AWS
              valueFrom:
                secretKeyRef:
                  name: env-config
                  key: ACCESS_KEY_ID_AWS

            - name: SECRET_ACCESS_KEY_AWS
              valueFrom:
                secretKeyRef:
                  name: env-config
                  key: SECRET_ACCESS_KEY_AWS

            - name: ALGOLIA_APPLICATION_ID
              valueFrom:
                secretKeyRef:
                  name: env-config
                  key: ALGOLIA_APPLICATION_ID

            - name: ALGOLIA_SEARCH_ONLY_API_KEY_ID
              valueFrom:
                secretKeyRef:
                  name: env-config
                  key: ALGOLIA_SEARCH_ONLY_API_KEY_ID

            - name: ALGOLIA_ADMIN_API_KEY_ID
              valueFrom:
                secretKeyRef:
                  name: env-config
                  key: ALGOLIA_ADMIN_API_KEY_ID

            - name: PORT
              valueFrom:
                secretKeyRef:
                  name: env-config
                  key: PORT

            - name: NATS_CLIENT_ID
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name

            - name: NATS_CLUSTER_ID
              value: tuskui

            - name: NATS_URL
              value: 'http:/nats-srv:4222/'
---
apiVersion: v1
kind: Service
metadata:
  name: board-srv
spec:
  selector:
    app: boards
  ports:
    - name: boards
      protocol: TCP
      port: 3000
      targetPort: 3000
